using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Data.Models;

public class Book
{
    /// <summary> Autogenerated by DB </summary>
    public string Id { get; set; } = string.Empty;

    public string Title { get; set; }
    public string Description { get; set; }
    public string Author { get; set; }

    public Book(string title, string description, string author)
    {
        Id = Guid.NewGuid().ToString();
        Title = title;
        Description = description;
        Author = author;
    }
}